// <auto-generated />
namespace Sklep.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Init9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init9));
        
        string IMigrationMetadata.Id
        {
            get { return "202401241702483_Init9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
